chore(deps): update deps roll-up aug-20-2016 (#892)
* chore(deps): update deps roll-up aug-20-2016

npm run setup
Tested Dev, Dev tunnel, Features, lang = de, NotFound, Production, off-line
npm run clean
npm run generate container Test /w defaults
npm run generate component TestComp /w defaults
use TestComp on TestPage
npm run generate route Test - /test
git commit -m "testing..."
npm start > localhost:3000/test

Node 6.3.1 npm 3.10.5 Mac OS 10.11.6
Chrome 52.0.2743.116 (64-bit)

chore(deps): update deps roll-up aug-20-2016

 react                  15.3.0  →  15.3.1
 react-dom              15.3.0  →  15.3.1
 react-router            2.6.1  →   2.7.0
 react-router-scroll     0.2.1  →   0.3.1 <--- rolled back
 redux-immutable         3.0.7  →   3.0.8
 babel-loader            6.2.4  →   6.2.5
 eslint                  3.3.0  →   3.3.1
 eslint-plugin-import   1.12.0  →  1.13.0
 eslint-plugin-react     6.0.0  →   6.1.2
 karma-chrome-launcher   1.0.1  →   2.0.0
 postcss-loader          0.9.1  →  0.10.1

ERROR: app.js?2de9:126 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_10_react_router_scroll___default(...) is not a function

Caused by  react-router-scroll         0.2.1  →   0.3.0

Rolled back to 0.2.1 apparently waiting for react-router 3 https://github.com/taion/react-router-scroll/issues/28

* chore(deps): remove unused history